CREATE TABLE IF NOT EXISTS users (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  username TEXT NOT NULL UNIQUE,
  pwd_hash TEXT NOT NULL DEFAULT '',
  pwd_ts INTEGER NOT NULL DEFAULT 0,
  salt TEXT NOT NULL DEFAULT '',
  base_path TEXT NOT NULL DEFAULT '/',
  role INTEGER NOT NULL DEFAULT 0,
  disabled INTEGER NOT NULL DEFAULT 0,
  permission INTEGER NOT NULL DEFAULT 0,
  otp_secret TEXT NOT NULL DEFAULT '',
  sso_id TEXT NOT NULL DEFAULT '',
  authn TEXT NOT NULL DEFAULT '[]',
  allow_ldap INTEGER NOT NULL DEFAULT 1,
  created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS settings (
  key TEXT PRIMARY KEY,
  value TEXT NOT NULL DEFAULT '',
  help TEXT NOT NULL DEFAULT '',
  type TEXT NOT NULL DEFAULT 'string',
  options TEXT NOT NULL DEFAULT '',
  group_id INTEGER NOT NULL DEFAULT 0,
  flag INTEGER NOT NULL DEFAULT 0,
  item_index INTEGER NOT NULL DEFAULT 0
);

CREATE TABLE IF NOT EXISTS storages (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  mount_path TEXT NOT NULL UNIQUE,
  storage_order INTEGER NOT NULL DEFAULT 0,
  driver TEXT NOT NULL DEFAULT 'Onedrive',
  cache_expiration INTEGER NOT NULL DEFAULT 30,
  custom_cache_policies TEXT NOT NULL DEFAULT '',
  status TEXT NOT NULL DEFAULT 'work',
  addition TEXT NOT NULL DEFAULT '{}',
  remark TEXT NOT NULL DEFAULT '',
  modified TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  disabled INTEGER NOT NULL DEFAULT 0,
  disable_index INTEGER NOT NULL DEFAULT 0,
  enable_sign INTEGER NOT NULL DEFAULT 0,
  order_by TEXT NOT NULL DEFAULT '',
  order_direction TEXT NOT NULL DEFAULT '',
  extract_folder TEXT NOT NULL DEFAULT '',
  web_proxy INTEGER NOT NULL DEFAULT 0,
  webdav_policy TEXT NOT NULL DEFAULT '302_redirect',
  proxy_range INTEGER NOT NULL DEFAULT 0,
  down_proxy_url TEXT NOT NULL DEFAULT '',
  disable_proxy_sign INTEGER NOT NULL DEFAULT 0
);

CREATE TABLE IF NOT EXISTS metas (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  path TEXT NOT NULL UNIQUE,
  read_users TEXT NOT NULL DEFAULT '[]',
  read_users_sub INTEGER NOT NULL DEFAULT 0,
  write_users TEXT NOT NULL DEFAULT '[]',
  write_users_sub INTEGER NOT NULL DEFAULT 0,
  password TEXT NOT NULL DEFAULT '',
  p_sub INTEGER NOT NULL DEFAULT 0,
  write INTEGER NOT NULL DEFAULT 0,
  w_sub INTEGER NOT NULL DEFAULT 0,
  hide TEXT NOT NULL DEFAULT '',
  h_sub INTEGER NOT NULL DEFAULT 0,
  readme TEXT NOT NULL DEFAULT '',
  r_sub INTEGER NOT NULL DEFAULT 0,
  header TEXT NOT NULL DEFAULT '',
  header_sub INTEGER NOT NULL DEFAULT 0
);

CREATE TABLE IF NOT EXISTS search_nodes (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  parent TEXT NOT NULL,
  name TEXT NOT NULL,
  is_dir INTEGER NOT NULL DEFAULT 0,
  size INTEGER NOT NULL DEFAULT 0,
  modified TEXT NOT NULL DEFAULT '',
  storage_id INTEGER NOT NULL DEFAULT 0,
  UNIQUE(parent, name, storage_id)
);

CREATE INDEX IF NOT EXISTS idx_search_nodes_name ON search_nodes(name);
CREATE INDEX IF NOT EXISTS idx_search_nodes_parent ON search_nodes(parent);

CREATE TABLE IF NOT EXISTS onedrive_tokens (
  storage_id INTEGER PRIMARY KEY,
  access_token TEXT NOT NULL DEFAULT '',
  refresh_token TEXT NOT NULL DEFAULT '',
  expires_at INTEGER NOT NULL DEFAULT 0,
  updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS sessions (
  token TEXT PRIMARY KEY,
  user_id INTEGER NOT NULL,
  expires_at INTEGER NOT NULL,
  created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS cache (
  key TEXT PRIMARY KEY,
  value TEXT NOT NULL,
  expires_at INTEGER NOT NULL
);
